[book]
authors = ["vachan-maker"]
language = "en"
multilingual = false
src = "src"
title = "Today I Learned"
[output.html]
git-repository-url = "https://github.com/vachan-maker/til"
edit-url-template = "https://github.com/vachan-maker/til/edit/main/{path}"
