[book]
authors = ["Vachan S Panicker"]
description = "Welcome to my personal wiki!. This is a place for me to just note down and share the things that I have learned."
language = "en"
multilingual = false
src = "src"
title = "Vachan's Wiki"
[output.html]
git-repository-url = "https://github.com/vachan-maker/til"
edit-url-template = "https://github.com/vachan-maker/til/edit/main/{path}"
